---
full_service_name: unificontroller
description: The Unifi-controller Controller software is a powerful, enterprise wireless software engine ideal for high-density client deployments requiring low latency and high uptime performance.
category: misc-other
version: latest
port: 8080
