# Job from R2Devops hub --> r2devops.io

stages:
  - static_tests
  - build
  - deploy

include:
  - remote: 'https://jobs.r2devops.io/latest/hugo.yml'
  - remote: 'https://jobs.r2devops.io/latest/mkdocs.yml'
  - remote: 'https://jobs.r2devops.io/pages.yml'

variables:
  GIT_SUBMODULE_STRATEGY: recursive

yaml_linter:
  image: 
    name: python:3.8.2
    entrypoint: [""]

  stage: static_tests

  script:
    - pip install yamllint
    - find . -type f -name '*.yml' | sed 's|\./||g' | egrep -v '(\.kitchen/|\[warning\]|\.molecule/)' | xargs yamllint -c yamllint.conf -f parsable

hugo:
  variables:
    HUGO_VERSION: "0.68.3"
  
  only:
    - master

mkdocs:
  variables:
    MKDOCS_OUTPUT_PATH: 'public/docs/'
  
  only:
    - master

pages:
  variables:
    PAGES_BUILD_PATH: 'public/'

  rules:
    - if: '$CI_COMMIT_BRANCH == "master"'
