# Job from R2Devops hub --> r2devops.io

stages:
  - static_tests
  - build
  - deploy

include:
  - remote: 'https://jobs.r2devops.io/latest/super_linter.yml'
  - remote: 'https://jobs.r2devops.io/latest/mkdocs.yml'
  - remote: 'https://jobs.r2devops.io/pages.yml'

super_linter:
  variables:
    VALIDATE_ANSIBLE: "false"
    VALIDATE_HTML: "false"
    VALIDATE_CSS: "false"
    VALIDATE_SHELL_SHFMT: "false"
    VALIDATE_DOCKERFILE: "false"
    VALIDATE_RUBY: "false"
    VALIDATE_JSON: "false"
    VALIDATE_MARKDOWN: "false"
    VALIDATE_PYTHON_PYLINT: "false"
    VALIDATE_PYTHON: "false"
    VALIDATE_JAVASCRIPT_ES: "false"
    VALIDATE_JAVASCRIPT_STANDARD: "false"

