# Job from R2Devops hub --> r2devops.io

## EVALUATION OF TIME ##
# 3 minutes for this pipeline to run in dev, against 1 minute for the current pipeline
# 4 minutes for this pipeline to run in master, against 1 minutes for the current pipeline

stages:
  - static_tests
  - build
  - deploy

include:
  #- remote: 'https://jobs.r2devops.io/latest/mega_linter.yml'
  - remote: 'https://jobs.r2devops.io/latest/super_linter.yml'
  - remote: 'https://jobs.r2devops.io/latest/mkdocs.yml'
  - remote: 'https://jobs.r2devops.io/pages.yml'

# We could be faster with the mega_linter since it is using a lighter image
.mega_linter:
  image:
    name: nvuillam/mega-linter-ci_light:v4

super_linter:
  before_script:
    - cp ${CI_PROJECT_DIR}/yamllint.conf /action/lib/.automation/yamllint.conf
  
  variables:
    YAML_CONFIG_FILE: "yamllint.conf"
    VALIDATE_YAML: "true"

hugo:
  image:
    name: golang:1.17.6-buster
    entrypoint: [""]

  stage: build

  variables:
    PROJECT_ROOT: "."
    HUGO_VERSION: "0.68.3"
    HUGO_SOURCE: "website"
    HUGO_OUTPUT: "public/"
    ADDITIONAL_OPTIONS: ""

  script:
    - cd ${PROJECT_ROOT}
    - curl -SL https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_${HUGO_VERSION}_Linux-64bit.tar.gz -o /tmp/hugo.tar.gz
    - tar -xzf /tmp/hugo.tar.gz -C /tmp
    - mv /tmp/hugo /usr/local/bin/
    - hugo -s ${HUGO_SOURCE} -d ${CI_PROJECT_DIR}/${HUGO_OUTPUT} ${ADDITIONAL_OPTIONS}

  artifacts:
    when: always
    paths:
      - ${CI_PROJECT_DIR}/${HUGO_OUTPUT}
  
  only:
    - master

mkdocs:
  variables:
    MKDOCS_OUTPUT_PATH: 'public/docs/'
  
  only:
    - master

pages:
  variables:
    PAGES_BUILD_PATH: 'public/'

  rules:
    - if: '$CI_COMMIT_BRANCH == "master"'
