# Job from R2Devops hub --> r2devops.io

stages:
  - static_tests
  - build
  - deploy

include:
  - remote: 'https://jobs.r2devops.io/latest/super_linter.yml'
  - remote: 'https://jobs.r2devops.io/latest/mkdocs.yml'
  - remote: 'https://jobs.r2devops.io/pages.yml'
