# Job from R2Devops hub --> r2devops.io

stages:
  - static_tests
  - build
  - deploy

include:
  - remote: 'https://jobs.r2devops.io/latest/super_linter.yml'
  - remote: 'https://jobs.r2devops.io/latest/mkdocs.yml'

pages:
  stage: deploy
  variables:
    PAGES_BUILD_PATH: 'website_build/'
  script:
    - if [ "$PAGES_BUILD_PATH" != "public" -a "$PAGES_BUILD_PATH" != "public/" ]; then
    -   if [ -d "public" ]; then rm -rf public; fi
    -   mv "$PAGES_BUILD_PATH" public
    - fi

    - if [ ! -d "public" ]; then echo "Nothing to deploy"; exit 1; fi
  artifacts:
    paths:
      - public
    when: always

super_linter:
  variables:
    VALIDATE_ANSIBLE: "false"
    VALIDATE_HTML: "false"
    VALIDATE_CSS: "false"
    VALIDATE_SHELL_SHFMT: "false"
    VALIDATE_DOCKERFILE: "false"
    VALIDATE_RUBY: "false"
    VALIDATE_JSON: "false"
    VALIDATE_MARKDOWN: "false"
    VALIDATE_PYTHON_PYLINT: "false"
    VALIDATE_PYTHON: "false"
    VALIDATE_JAVASCRIPT_ES: "false"
    VALIDATE_JAVASCRIPT_STANDARD: "false"

