---
# Initial setup so Ansible can actually work.
- name: Install python (required by Ansible).
  gather_facts: "False"
  hosts: all
  become: "True"
  become_method: sudo
  pre_tasks:
    - name: 'Update Apt Cache'
      raw: sudo apt-get update
      ignore_errors: True
    - name: 'Install Python'
      raw: sudo apt-get -y install python-simplejson

# Configure the server itself
- hosts: homelabos
  become: "True"
  gather_facts: "True"
  tags: common

  roles:
    # Install Docker, configure basic server settings
    - homelabos_common
    # Configure a TOR hidden service for remote access without a public IP
    - role: tor
      hidden_services:
        - dir: /var/lib/tor/ssh-onion
          port: 22
          source: 127.0.0.1:22
        - dir: /var/lib/tor/https-onion
          port: 443
          source: 127.0.0.1:443
        - dir: /var/lib/tor/http-onion
          port: 80
          source: 127.0.0.1:80

# Install and configure HomelabOS services
- hosts: homelabos
  become: "True"
  gather_facts: "True"
  tags:
    - homelabos
    - deploy
  roles:
    - homelabos_base

# Install and configure HomelabOS documentation
- hosts: homelabos
  become: "True"
  gather_facts: "True"
  tags:
    - homelabos
    - docs
  roles:
    - role: homelabos_docs
      when: enable_docs

- name: "Setup tinc VPN"
  tags: tinc
  hosts: all
  become: yes
  become_method: sudo
  roles:
    - role: homelabos_tinc
      when:
        - "vpn_ip is defined"

- name: "Update Tinc NGINX Servers"
  hosts: tinc
  become: yes
  become_method: sudo
  tags: tinc-nginx
  roles:
    - role: homelabos_tinc-nginx
      when:
        - "vpn_ip is defined"

- name: "Deploy enabled services"
  hosts: homelabos
  become: "True"
  gather_facts: "True"
  tags:
    - deploy
  roles:
    - role: apple_health_influx
      when: enable_apple_health_influx
    - role: bitwarden
      when: enable_bitwarden
    - role: bulletnotes
      when: enable_bulletnotes
    - role: bitwarden
      when: enable_bitwarden
    - role: firefly_iii
      when: enable_firefly_iii
    - role: thelounge
      when: enable_thelounge

...
