---

- name: Setup {{service_item}}
  include: includes/setup.yml

- name: Make additional code-server directories.
  file:
    path: "{{ item }}"
    state: directory
    mode: 0777
  loop:
    - "{{ volumes_root }}/codeserver/.local"
    - "{{ volumes_root }}/codeserver/project"

- name: Start {{service_item}}
  include: includes/start.yml
