---
- name: Make apache2 directory.
  file:
    path: "{{ volumes_root }}/apache2"
    state: directory

- name: Check for existence of httpd.conf
  stat:
    path: "{{ volumes_root }}/apache2/httpd.conf"
  register: httpd_conf_file

- name: Copy default apache config from docker image
  shell:
    cmd: "docker run --rm httpd:2.4 cat /usr/local/apache2/conf/httpd.conf > {{ volumes_root }}/apache2/httpd.conf"
  when: not httpd_conf_file.stat.exists

- name: Copy apache2 docker-compose.yml file into place.
  template:
    src: docker-compose.apache2.yml.j2
    dest: "{{ volumes_root }}/apache2/docker-compose.yml"
  vars:
    tor_domain: "{{ tor_http_domain_file.stdout | default('') }}"

- name: Configure apache2 systemd service.
  template:
    src: service.j2
    dest: /etc/systemd/system/apache2.service

- name: Start apache2
  systemd:
    name: apache2
    enabled: "yes"
    daemon-reload: "yes"
    state: started
