---
  - hosts: localhost
    tasks:
      - name: Amazon Dash
        
        docker_image:
          image: hijinx/dasher
          restart: always
          network_mode: host
          volumes:
            - /var/homelabos/dasher/config.json:/usr/src/app/config/config.json
          