---
  - hosts: localhost
    tasks:
    - name: influxdb
      docker_image:
        image: influxdb
        restart: always
        volumes:
          - /var/homelabos/influxdb:/var/lib/influxdb
        ports:
          - 8086:8086