---
  - hosts: localhost
    tasks: 
    - name: koel_database
      docker_image:
        image: mariadb
        restart: always
        volumes:
          - /var/homelabos/koel/db:/var/lib/mysql
        environment:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: koel
          MYSQL_USER: koel
          MYSQL_PASSWORD: koel
