---
  - hosts: localhost
    tasks:
    - name: monicahq
      docker_image:
        image: monicahq/monicahq
        restart: always
        links:
          - monicahq_db
        ports:
          - 8176:80
        volumes:
          - /var/homelabos/monica/storage/app/public:/var/www/monica/storage/app/public
        labels:
          - "traefik.enable=true"
          - "traefik.http.frontend.rule=Host:monica.{{ domain }}"
          - "traefik.http.frontend.headers.customFrameOptionsValue=ALLOW-FROM http://{{ domain }}"
          - "traefik.http.frontend.headers.customFrameOptionsValue=ALLOW-FROM https://{{ domain }}"
          - "traefik.http.protocol={{ protocol }}"
          - "traefik.http.port=80"
          - "traefik.tor.frontend.rule=Host:monica.{{ tor_domain }}"
          - "traefik.tor.protocol={{ protocol }}"
          - "traefik.tor.port=80"
        env_file:
          - /var/homelabos/docker/monica.env
