---
  - name: nextcloud
    docker_container:
      image: nextcloud
      depends_on: nextcloud_db
      restart: always
      links:
        - nextcloud_db
      volumes:
        - /var/homelabos/nextcloud:/var/www/html
        - /mnt/nas/Documents/Nextcloud:/var/www/html/data
      restart: always
      environment:
        - MYSQL_DATABASE=nextcloud
        - MYSQL_USER=nextcloud
        - MYSQL_PASSWORD=nextcloud
        - MYSQL_HOST=nextcloud_db
        - NEXTCLOUD_ADMIN_USER={{ default_username }}
        - NEXTCLOUD_ADMIN_PASSWORD={{ default_password }}
      labels:
        - "traefik.enable=true"
        - "traefik.http.frontend.rule=Host:nextcloud.{{ domain }}"
        - "traefik.http.frontend.headers.customFrameOptionsValue=ALLOW-FROM http://{{ domain }}"
        - "traefik.http.frontend.headers.customFrameOptionsValue=ALLOW-FROM https://{{ domain }}"
        - "traefik.http.protocol={{ protocol }}"
        - "traefik.http.port=80"
        - "traefik.tor.frontend.rule=Host:nextcloud.{{ tor_domain }}"
        - "traefik.tor.protocol={{ protocol }}"
        - "traefik.tor.port=80"
