---
  - hosts: localhost
    tasks:
    - name: openvpn
      docker_image:
        cap_add:
        - NET_ADMIN
        image: kylemanna/openvpn
        ports:
        - "1194:1194/udp"
        restart: always
        volumes:
        - /var/homelabos/openvpn:/etc/openvpn
