---
  - hosts: localhost
    tasks:
    - name: pihole
      docker_image:
        image: pihole/pihole:latest
        restart: always
        volumes:
          - /var/homelabos/pihole/config/:/etc/pihole/
          - /var/homelabos/pihole/dnsmasq.d/:/etc/dnsmasq.d/
        environment:
          - WEBPASSWORD={{ default_password }}
          - VIRTUAL_HOST=pihole.{{ domain }}
          - ServerIP={{ ansible_ssh_host }}
        # ports:
        #   - 53:53/tcp
        #   - 53:53/udp
        labels:
          - "traefik.enable=true"
          - "traefik.http.frontend.rule=Host:pihole.{{ domain }}"
          - "traefik.http.protocol={{ protocol }}"
          - "traefik.http.port=80"
          - "traefik.http.frontend.headers.customFrameOptionsValue=ALLOW-FROM https://{{ domain }}"
          - "traefik.tor.frontend.rule=Host:pihole.{{ tor_domain }}"
          - "traefik.tor.protocol={{ protocol }}"
          - "traefik.tor.port=80"
        extra_hosts:
          - docker.{{ domain }}:{{ ansible_ssh_host }}
          - docs.{{ domain }}:{{ ansible_ssh_host }}
          - emby.{{ domain }}:{{ ansible_ssh_host }}
          - plex.{{ domain }}:{{ ansible_ssh_host }}
          - git.{{ domain }}:{{ ansible_ssh_host }}
          - grafana.{{ domain }}:{{ ansible_ssh_host }}
          - homeassistant.{{ domain }}:{{ ansible_ssh_host }}
          - irc.{{ domain }}:{{ ansible_ssh_host }}
          - koel.{{ domain }}:{{ ansible_ssh_host }}
          - matomo.{{ domain }}:{{ ansible_ssh_host }}
          - mastodon.{{ domain }}:{{ ansible_ssh_host }}
          - minio.{{ domain }}:{{ ansible_ssh_host }}
          - money.{{ domain }}:{{ ansible_ssh_host }}
          - monica.{{ domain }}:{{ ansible_ssh_host }}
          - music.{{ domain }}:{{ ansible_ssh_host }}
          - nextcloud.{{ domain }}:{{ ansible_ssh_host }}
          - paperless.{{ domain }}:{{ ansible_ssh_host }}
          - pihole.{{ domain }}:{{ ansible_ssh_host }}
          - portainer.{{ domain }}:{{ ansible_ssh_host }}
          - radarr.{{ domain }}:{{ ansible_ssh_host }}
          - terminal.{{ domain }}:{{ ansible_ssh_host }}
          - torrent.{{ domain }}:{{ ansible_ssh_host }}
          - warden.{{ domain }}:{{ ansible_ssh_host }}
