---
  - hosts: localhost
    tasks:
    - name: sonarr
      docker_image:
        image: linuxserver/sonarr
        restart: always
        environment:
          - PGID=1000
          - PUID=1000
          - TZ={{ timezone }}
        links:
          - jackett
          - transmission
        volumes:
          - /etc/localtime:/etc/localtime:ro
          - /var/homelabos/sonarr/config:/config
          - /mnt/nas/TV:/tv
          - /var/homelabos/sonarr/downloads:/downloads
        labels:
          - "traefik.enable=true"
          - "traefik.http.frontend.rule=Host:sonarr.{{ domain }}"
          - "traefik.http.protocol={{ protocol }}"
          - "traefik.http.port=8989"
          - "traefik.tor.frontend.rule=Host:sonarr.{{ tor_domain }}"
          - "traefik.tor.protocol={{ protocol }}"
          - "traefik.tor.port=8989"
