---
- name: Make wordpress directory.
  file:
    path: "{{ volumes_root }}/wordpress"
    state: directory

- name: Copy wordpress docker-compose.yml file into place.
  template:
    src: docker-compose.wordpress.yml.j2
    dest: "{{ volumes_root }}/wordpress/docker-compose.yml"
  vars:
    tor_domain: "{{ tor_http_domain_file.stdout | default('') }}"

- name: Configure wordpress systemd service.
  template:
    src: service.j2
    dest: /etc/systemd/system/wordpress.service

- name: Start wordpress
  systemd:
    name: wordpress
    enabled: "yes"
    daemon-reload: "yes"
    state: started
...
