---

- name: Setup {{service_item}}
  include: includes/setup.yml

- name: Make zammads directories.
  file:
    path: "{{ item }}"
    state: directory
    mode: 0777
  loop:
    - "{{ volumes_root }}/zammad/zammad-data"
    - "{{ volumes_root }}/zammad/postgresql-data"
    - "{{ volumes_root }}/zammad/elasticsearch-data"
    - "{{ volumes_root }}/zammad/zammad-backup"

- name: Start {{service_item}}
  include: includes/start.yml
