---
- name: Make readarr directory.
  file:
    path: "{{ volumes_root }}/readarr"
    state: directory

- name: Get UID
  command: id -u {{ homelab_ssh_user }}
  register: uid_output
  become: false

- name: Get GID
  command: id -g {{ homelab_ssh_user }}
  register: gid_output
  become: false

- name: Copy readarr docker-compose.yml file into place.
  template:
    src: docker-compose.readarr.yml.j2
    dest: "{{ volumes_root }}/readarr/docker-compose.yml"
  vars:
    tor_domain: "{{ tor_http_domain_file.stdout | default('') }}"
    uid: "{{ uid_output.stdout }}"
    gid: "{{ gid_output.stdout }}"

- name: Configure readarr systemd service.
  template:
    src: service.j2
    dest: /etc/systemd/system/readarr.service

- name: Start readarr
  systemd:
    name: readarr
    enabled: "yes"
    daemon-reload: "yes"
    state: started
