---
  - name: openvpn
    docker_container:
      cap_add:
      - NET_ADMIN
      image: kylemanna/openvpn
      ports:
      - "1194:1194/udp"
      restart: always
      volumes:
      - /var/homelabos/openvpn:/etc/openvpn
