---
  - name: paperless_consumer
    docker_container:
      image: danielquinn/paperless
      restart: always
      depends_on:
        - paperless
      volumes:
        - /var/homelabos/paperless/data:/usr/src/paperless/data
        - /var/homelabos/paperless/media:/usr/src/paperless/media
        - /mnt/nas/Documents/consume:/consume
        - /mnt/nas/Documents/export:/export
      environment:
        - PAPERLESS_PASSPHRASE=homelabos
      command: ["document_consumer"]
