---
  - name: xfinityusageinfluxdb
    docker_container:
      image: nickbusey/xfinityusageinfluxdb
      restart: unless-stopped
      links:
        - influxdb
      environment:
        - XFINITY_USER={{ xfinity_user }}
        - XFINITY_PASSWORD={{ xfinity_password }}
        - INFLUXDB_HOST=influxdb
