---

- name: Setup {{service_item}}
  include: includes/setup.yml

- name: Configure telegraf
  template:
    src: telegraf.conf.j2
    dest: "{{ volumes_root }}/tick/telegraf.conf"

- name: Start {{service_item}}
  include: includes/start.yml
