---

- name: Setup {{service_item}}
  include: includes/setup.yml

- name: Make funkwhale media directory.
  file:
    path: "{{ volumes_root }}/funkwhale/media"
    state: directory

- name: Start {{service_item}}
  include: includes/start.yml
