---
- name: Make pleroma directory.
  file:
    path: "{{ volumes_root }}/pleroma"
    state: directory

- name: Copy pleroma docker-compose.yml file into place.
  template:
    src: docker-compose.pleroma.yml.j2
    dest: "{{ volumes_root }}/pleroma/docker-compose.pleroma.yml"
  vars:
    tor_domain: "{{ tor_http_domain_file.stdout | default('') }}"

- name: Configure upload directory
  file:
    state: directory
    path: {{ volumes_root }}/pleroma/upload
    owner: "{{ ansible_effective_user_id }}"
    group: "{{ ansible_effective_group_id }}"
    recurse: yes

- name: Configure config directory
  file:
    state: directory
    path: {{ volumes_root }}/pleroma/config
    owner: "{{ ansible_effective_user_id }}"
    group: "{{ ansible_effective_group_id }}"
    recurse: yes

- name: Copy pleroma docker file into place.
  template:
    src: Dockerfile
    dest: "{{ volumes_root }}/pleroma/Dockerfile"

- name: Generate Pleroma Secret Key Base
  shell: >
    openssl rand -base64 48
  register: secret_key

- name: Copy Secret.exs into place.
  template:
    src: secret.exs
    dest: "{{ volumes_root }}/pleroma/config/secret.exs"
  vars: 
    secret_key: secret_key

- name: Build Docker Image
  shell: >
    docker build -t pleroma .

- name: Install CIText postgres extension
  shell: >
    docker-compose -f {{ volumes_root}}/pleroma/docker-compose.pleroma.yml run pleroma_postgress --rm exec psql -U pleroma -c "CREATE EXTENSION IF NOT EXISTS citext;"

- name: Run DB migrations
  shell: >
    docker-compose -f {{ volumes_root}}/pleroma/docker-compose.pleroma.yml run --rm web mix ecto.migrate

- name: Capture web push keys
  shell: >
    docker-compose run --rm web mix web_push.gen.keypair
  register: keypair

- name: Configure pleroma systemd service.
  template:
    src: service.j2
    dest: /etc/systemd/system/pleroma.service

- name: Start pleroma
  systemd:
    name: pleroma
    enabled: "yes"
    daemon-reload: "yes"
    state: started
