---

- name: Setup {{service_item}}
  include: includes/setup.yml

- name: Configure Dasher
  template:
    src: dasher.config.json
    dest: "{{ volumes_root }}/{{service_item}}/config.json"

- name: Start {{service_item}}
  include: includes/start.yml
