---
- name: Make speedtest_tracker directory.
  file:
    path: "{{ volumes_root }}/speedtest_tracker"
    state: directory

- name: Copy speedtest_tracker docker-compose.yml file into place.
  template:
    src: docker-compose.speedtest_tracker.yml.j2
    dest: "{{ volumes_root }}/speedtest_tracker/docker-compose.yml"
  vars:
    tor_domain: "{{ tor_http_domain_file.stdout | default('') }}"

- name: Configure speedtest_tracker systemd service.
  template:
    src: service.j2
    dest: /etc/systemd/system/speedtest_tracker.service

- name: Start speedtest_tracker
  systemd:
    name: speedtest_tracker
    enabled: "yes"
    daemon-reload: "yes"
    state: started
