---

- name: Stop Services.
  systemd:
    name: "{{service_item}}""
    enabled: no
    daemon-reload: "yes"
    state: stopped
  when: "enabled_services[service_item]"
  loop: "{{ services|flatten(levels=1) }}"
  loop_control:
    loop_var: service_item

- name: remove enabled services.
  file:
    state: absent
    path: "/var/homelabos/{{service_item}}"
  when: "enabled_services[service_item]"
  loop: "{{ services|flatten(levels=1) }}"
  loop_control:
    loop_var: service_item

- name: Remove Service file
  file: 
    state: absent
    path: "/etc/systemd/system/{{service_item}}.service"
  when: "enabled_services[service_item]"
  loop: "{{ services|flatten(levels=1) }}"
  loop_control:
    loop_var: service_item

- debug:
    msg: "Package removed successfully! Go to https://{{ domain }}/ to get started."

- debug:
    msg: "Problems? File an issue at https://gitlab.com/NickBusey/HomelabOS/issues"
