---
#####################################
## What this playbook does:
## - Install minimal on-host dependencies to get docker running
#####################################
- name: Install minimal system packages for adding Docker-ce repo
  apt: name={{ item }} state=latest update_cache=yes
  loop: ['gnupg-agent']
  become: yes

# https://docs.docker.com/engine/install/debian/
- name: Add Docker GPG apt Key for distro {{ homelabos_distribution }}
  apt_key:
    url: https://download.docker.com/linux/{{ homelabos_distribution|lower }}/gpg
    state: present
  become: yes

- name: Add Docker Repository for distro {{ homelabos_distribution }} - {{ homelabos_distribution_release }}.
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/{{ homelabos_distribution|lower }} {{ homelabos_distribution_release|lower }} stable
    state: present
  become: yes

- name: Update apt and install docker-ce
  apt: name={{ item }} state=latest update_cache=yes
  loop: ['docker-ce', 'docker-ce-cli', 'containerd.io', 'docker-compose']
  become: yes

- name: Configure docker log settings
  copy:
    src: daemon.json
    dest: /etc/docker/daemon.json
  become: yes
